name: CityBuild
version: '${project.version}'
main: de.murmelmeister.citybuild.CityBuild
api-version: 1.19
authors: [ Murmelmeister ]
description: The main system for the citybuild.
website: https://www.youtube.com/Murmelmeister

commands:
  citybuild:
    usage: /<command> [reload]
    description: Admin command edit the plugin.
  setspawn:
    usage: /<command>
    description: Set the spawn.
  spawn:
    usage: /<command>
    description: Teleport you to the spawn.
  sethome:
    usage: /<command> <homes>
    description: Erstelle dein Home.
  home:
    usage: /<command> <homes>
    description: Teleport dich zu deinem Home.
  deletehome:
    usage: /<command> <homes>
    description: Lösche dein Home.
    aliases: [ delhome ]
  pay:
    usage: /<command> <players> <coin>
    description: Bezahle andere Spieler.
  money:
    usage: /<command> [players]
    description: Zeige dein Kontostand an.