name: CityBuild
version: '${project.version}'
main: de.murmelmeister.citybuild.CityBuild
api-version: 1.19
authors: [ Murmelmeister ]
description: The main system for the citybuild.
website: https://www.youtube.com/Murmelmeister

commands:
  citybuild:
    usage: /<command> [reload]
    description: Admin command edit the plugin.
  setspawn:
    usage: /<command>
    description: Set the spawn.
  spawn:
    usage: /<command>
    description: Teleport you to the spawn.
  sethome:
    usage: /<command> <homes>
    description: Set you home!
  home:
    usage: /<command> <homes>
    description: Teleport to you home!
  deletehome:
    usage: /<command> <homes>
    description: Delete you home!
    aliases: [ delhome ]